apiVersion: v2
appVersion: 1.0.0
dependencies:
- condition: kepler.deploy
  name: kepler
  repository: https://sustainable-computing-io.github.io/kepler-helm-chart
  version: 0.6.1
- alias: node-exporter
  condition: node-exporter.deploy
  name: prometheus-node-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.56.1
- alias: windows-exporter
  condition: windows-exporter.deploy
  name: prometheus-windows-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 0.12.8
- condition: kube-state-metrics.deploy
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 8.4.0
- condition: opencost.deploy
  name: opencost
  repository: oci://ghcr.io/opencost/charts
  version: 2.5.29
- alias: k8s-manifest-tail
  condition: k8s-manifest-tail.deploy
  name: k8s-manifest-tail
  repository: https://grafana.github.io/helm-charts
  version: 0.1.5
- condition: beyla.deploy
  name: beyla
  repository: https://grafana.github.io/helm-charts
  version: 1.16.11
- alias: sdkInjector
  condition: sdkInjector.deploy
  name: k8s-injection-controller
  repository: https://grafana.github.io/helm-charts
  version: 0.2.1
description: Additional Deployments to generate observability telemetry data
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
maintainers:
- email: pete.wall@grafana.com
  name: petewall
- email: tyler.helmuth@grafana.com
  name: TylerHelmuth
name: telemetry-services
sources:
- https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/telemetry-services
version: 1.0.0
