apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-manifest-tail.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-manifest-tail.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-manifest-tail.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-manifest-tail.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ toYaml .Values.config | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "k8s-manifest-tail.serviceAccountName" . }}
      {{- include "k8s-manifest-tail.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: k8s-manifest-tail
          image: {{ include "k8s-manifest-tail.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
            - --config
            - /etc/k8s-manifest-tail/config.yaml
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/k8s-manifest-tail
              readOnly: true
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "k8s-manifest-tail.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
