apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # UniFi controller credentials (ESO)
  - external-secret.yaml
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 5.1.0
    releaseName: unpoller
    namespace: unpoller
    valuesFile: values.yaml
