apiVersion: v2
appVersion: 0.2.0
description: Kubernetes admission controller for Grafana Beyla SDK auto-instrumentation.
keywords:
- observability
- autoinstrumentation
- OpenTelemetry
maintainers:
- name: mariomac
  url: https://github.com/mariomac
- name: grcevski
  url: https://github.com/grcevski
- name: jack-berg
  url: https://github.com/jack-berg
- name: jaydeluca
  url: https://github.com/jaydeluca
name: k8s-injection-controller
type: application
version: 0.2.1
