apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 5.1.0
    releaseName: seerr
    namespace: seerr
    valuesFile: values.yaml
