apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-injection-controller.webhookServiceName" . }}
  namespace: {{ include "k8s-injection-controller.namespace" . }}
  labels:
    {{- include "k8s-injection-controller.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "k8s-injection-controller.selectorLabels" . | nindent 4 }}
