apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Grafana Cloud endpoints + credentials (ESO)
  - external-secret.yaml
helmCharts:
  - name: k8s-monitoring
    repo: https://grafana.github.io/helm-charts
    version: 4.5.0
    releaseName: monitoring
    namespace: monitoring
    includeCRDs: true
    valuesFile: values.yaml
