apiVersion: v2
appVersion: 1.11.1
dependencies:
- condition: crds.deployAlloyCRD
  name: alloy-crd
  repository: https://grafana.github.io/helm-charts
  version: 1.0.1
- condition: crds.deployPodLogsCRD
  name: podlogs-crd
  repository: ""
  version: 0.0.0
description: Grafana Alloy Operator, providing innovative ways for creating instances
  of Grafana Alloy.
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
maintainers:
- email: pete.wall@grafana.com
  name: petewall
- email: tyler.helmuth@grafana.com
  name: TylerHelmuth
name: alloy-operator
sources:
- https://github.com/grafana/alloy-operator
type: application
version: 0.6.3
