apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: birdnet-go
spec:
  selector:
    app.kubernetes.io/controller: mariadb
    app.kubernetes.io/instance: birdnet-go
    app.kubernetes.io/name: birdnet-go
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
