apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Controller credentials (ESO)
  - external-secret.yaml
helmCharts:
  - name: cloudflare-tunnel-ingress-controller
    repo: https://helm.strrl.dev
    version: 0.1.0
    releaseName: cloudflare-tunnel-ingress-controller
    namespace: cloudflare-tunnel
    valuesFile: values.yaml
